package entities;
// Generated Sep 20, 2015 7:16:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name="Bill"
    ,schema="dbo"
    ,catalog="CoffeeShopAptech"
)
public class Bill  implements java.io.Serializable {


     private Integer id;
     private Account account;
     private String customerName;
     private BigDecimal total;
     private Date date;
     private boolean isActive;
     private Set<ProductBill> productBills = new HashSet<ProductBill>(0);

    public Bill() {
    }

	
    public Bill(Account account, BigDecimal total, Date date, boolean isActive) {
        this.account = account;
        this.total = total;
        this.date = date;
        this.isActive = isActive;
    }

    public Bill(Account account, String customerName, BigDecimal total, Date date, boolean isActive) {
        this.account = account;
        this.customerName = customerName;
        this.total = total;
        this.date = date;
        this.isActive = isActive;
    }
    
    public Bill(Account account, String customerName, BigDecimal total, Date date, boolean isActive, Set<ProductBill> productBills) {
       this.account = account;
       this.customerName = customerName;
       this.total = total;
       this.date = date;
       this.isActive = isActive;
       this.productBills = productBills;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SellerID", nullable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

    
    @Column(name="CustomerName")
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="Total", nullable=false, precision=18)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Date", nullable=false, length=23)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="IsActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bill")
    public Set<ProductBill> getProductBills() {
        return this.productBills;
    }
    
    public void setProductBills(Set<ProductBill> productBills) {
        this.productBills = productBills;
    }




}


