package entities;
// Generated Sep 20, 2015 7:16:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductBill generated by hbm2java
 */
@Entity
@Table(name="Product_Bill"
    ,schema="dbo"
    ,catalog="CoffeeShopAptech"
)
public class ProductBill  implements java.io.Serializable {


     private Integer id;
     private Bill bill;
     private Product product;
     private int quantity;
     private BigDecimal price;

    public ProductBill() {
    }

    public ProductBill(Bill bill, Product product, int quantity, BigDecimal price) {
       this.bill = bill;
       this.product = product;
       this.quantity = quantity;
       this.price = price;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BillID", nullable=false)
    public Bill getBill() {
        return this.bill;
    }
    
    public void setBill(Bill bill) {
        this.bill = bill;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProductID", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="Quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="Price", nullable=false, precision=18)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


