package entities;
// Generated Sep 20, 2015 7:16:35 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleFunction generated by hbm2java
 */
@Entity
@Table(name="Role_Function"
    ,schema="dbo"
    ,catalog="CoffeeShopAptech"
)
public class RoleFunction  implements java.io.Serializable {


     private Integer id;
     private Functions functions;
     private Role role;

    public RoleFunction() {
    }

    public RoleFunction(Functions functions, Role role) {
       this.functions = functions;
       this.role = role;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FunctionID", nullable=false)
    public Functions getFunctions() {
        return this.functions;
    }
    
    public void setFunctions(Functions functions) {
        this.functions = functions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RoleID", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }




}


